### ISSUE TITLE
We can use Comparator for sorting

### ISSUE THREAD

**Issue by nierraj** [thorat-datta24/sai-praveen#2]
https://github.com/thorat-datta24/sai-praveen/blob/3433f78e8e9c3eac0ca4a93f5d584d28b710cdde/sai-pravin/src/com/nisum/saipravin/assignments/arraylist/ArrayListSort.java#L52

**Comment by saiventuri** [comment]
It is instructed to me to write a logic for sort instead of using inbuilt constructs, so i written bubble sort logic.
