### ISSUE TITLE
Is this part of assignments? Is it for duplicate Hashtable keys or same hash of objects?

### ISSUE THREAD

**Issue by nierraj** [thorat-datta24/sai-praveen#3]
https://github.com/thorat-datta24/sai-praveen/blob/3433f78e8e9c3eac0ca4a93f5d584d28b710cdde/sai-pravin/src/com/nisum/saipravin/assignments/collections/Student.java#L76

**Comment by saiventuri** [comment]
This Class was written to demonstrate duplicate values in a hash set. This was used in HashSetDuplicateKeyImpl.java assignment.
